server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://192.168.0.152:33306/jeeplatform?autoReconnect=true&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false
    username: root
    password: minstone
    driver-class-name: com.mysql.jdbc.Driver
  main:
    allow-bean-definition-overriding: true
